name: CI for KMeans App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.14.0

    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Python dependencies
      run: |
        make install

    - name: Run tests
      run: |
        make run
